Sprint 4
nt-training-july-2023/Praveen_Assignments pull request #4
Opened 2023-09-29 10:36 UTC by Praveen-Nucleusteq

2023-09-29 11:04 UTC, Aashi-nucleus requested changes

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/Pages/EmployeeDashboard/Cards/MyProfile.jsx
> +        `http://localhost:8080/api/employee/id/${id}`
Use common functions for API integration. Don't use endpoints directly here.

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/Pages/EmployeeDashboard/Cards/MyProfile.jsx
> +      console.log(error);
Remove consoles

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/Pages/EmployeeDashboard/Cards/MyProfile.jsx
> +            {/* </div> */}
Remove commented code

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/Pages/EmployeeDashboard/Cards/Organization.css
> +    /* display: flex;
Remove commented codes

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/Pages/EmployeeDashboard/Cards/Organization.jsx
> +    // const [projects, setProjects] = useState([]);
Remove commented codes.

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/Pages/EmployeeDashboard/Cards/Organization.jsx
> +        console.error("Error fetching data:", error);
Remove consoles

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/Pages/EmployeeDashboard/EmployeeDashboard.css
> +/*
Remove commented codes

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/Pages/EmployeeDashboard/EmployeeDashboard.jsx
> +      // <div>UnauthrizedAccess</div>
Remove commented codes.

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/Pages/EmployeeDashboard/EmployeeDashboard.jsx
> +          <button className="ED-logout-btn" onClick={logout}>
Use common components for buttons, inputs, form, card etc.

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/Pages/EmployeeDashboard/UpdateSkills.css
> +      /* width: 300px;
Remove commented codes

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/Pages/EmployeeDashboard/UpdateSkills.jsx
> +          `http://localhost:8080/api/updateSkill/${employeeId}`,
Use common functions for API integration. Don't use endpoints directly here.

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/Pages/EmployeeDashboard/UpdateSkills.jsx
> +          <button type="button" onClick={handleUpdate}>
Use common components for button

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/Pages/ManagerDashboard/Cards/EmployeeCard.jsx
> +  // const notify=()=>{
Remove commented codes

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/Pages/ManagerDashboard/Cards/EmployeeCard.jsx
> +      console.error("Error fetching data:", error);
Remove consoles from everywhere.

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/Pages/ManagerDashboard/Cards/EmployeeCard.jsx
> +// }
Remove commented codes

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/Pages/ManagerDashboard/Cards/EmployeeCarddd.css
> +    /* display: flex;
Remove commented codes

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/Pages/ManagerDashboard/ManagerDashboard.jsx
> +            <button className="MD-logout-btn" onClick={logout}>
Use common component for button

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/Pages/ManagerDashboard/RequestResource.css
> +      /* width: 300px;
Remove commented codes

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/Pages/ManagerDashboard/RequestResource.jsx
> +import { toast } from "react-toastify"; // Import toast and ToastContainer from react-toastify
Remove commented codes

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/Pages/ManagerDashboard/RequestResource.jsx
> +        console.error("Error fetching data:", error);
Remove consoles

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/Pages/ManagerDashboard/RequestResource.jsx
> +          "http://localhost:8080/api/requestResource",
Use common functions for API integration instead of using endpoints directly.

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/components/AddEmployee/AddEmployee.jsx
> +import { Slide, toast } from "react-toastify"; // Import toast and ToastContainer from react-toastify
Remove commented code

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/components/AddEmployee/AddEmployee.jsx
> +    console.log(DefaultPassword);
Remove consoles

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/components/AddProject/AddProject.css
> +    /* background:linear-gradient(#33ccff , #660066); */
Remove commented codes

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/components/AddProject/AddProject.jsx
> +  //   const [skills,setSkills]=useState([
Remove commented codes

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/components/AddProject/AddProject.jsx
> +      const response = await axios.get("http://localhost:8080/api/all/Manager");
Use common functions for API integration instead of using endpoints directly.

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/components/AdminDashboard/AdminDashboard.css
> +  width: 100%;
Remove commented codes

2023-09-29 11:04 UTC, Aashi-nucleus commented on Capstone/Frontend/employeemanagementsystem-app/src/index.css
> +    /* overflow-y: scroll; */
Remove comments

2023-10-04 11:21 UTC, closed without merging

2023-10-04 11:22 UTC, Praveen-Nucleusteq commented
reviewed